### ISSUE TITLE
[Bug] Simulation fails

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1898]
Open the attached design file and go to the Flight simulations tab. Add a simulation using the Estes E12-0 motor and close the pane without running the simulation. Then run the simulation from the Fight simulation tab.

![Time](https://user-images.githubusercontent.com/68821492/208264328-85eee803-b928-4ff0-b738-586e91bbac25.png)

[01.03.01.Motor Mount.24mm.Estes 95mm Engine Hook.ork.txt](https://github.com/openrocket/openrocket/files/10252661/01.03.01.Motor.Mount.24mm.Estes.95mm.Engine.Hook.ork.txt)

[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by JoePfeiffer** [comment]
I'm not sure this is even a bug...  I'll see about either putting a clamp on the simulation step and/or putting up an exception for a "rocket" that's got so little aerodynamic surfaces it can't be simulated.

**Comment by hcraigmiller** [comment]
Fixed by way of PR #1914]

**Comment by JoePfeiffer** [comment]
No, #1914 is just helping me find what's going on with this.  The simulation is still failing on an exception.

Trying to solve this one is an interesting exercise, but in spite of the labels I'm not sure it's really any kind of blocker.  Basically a totally ridiculous simulation fails.  My current plans on solving it are --

1. see if I can find a way to limit the sim step size to keep crazy aerodynamics from provoking a numerical instability.  This shouldn't be difficult, but I need to look at it seriously in the morning.
2. if not, see if I can characterize "crazy" in a way that can bring up a popup refusing to even try.  This one has a zero-length total external symmetric components so it would be easy to identify if the first idea is too hard; is there a more general characterization?
3. punt.  Anybody who tries to sim a naked motor mount really deserves what they get...
