### ISSUE TITLE
angle number not changing ?

### ISSUE THREAD

**Issue by Teals53** [openrocket/openrocket#553]
its 0

![image](https://user-images.githubusercontent.com/13446881/66783880-9a94b500-eee1-11e9-91a0-b02569d22099.png)

still 0 ?
![image](https://user-images.githubusercontent.com/13446881/66783885-9ff1ff80-eee1-11e9-9495-ed46ae7d75c9.png)

**Comment by neilweinstock** [comment]
I *think* that 0 is just intended to indicate that the top of the slider represents 0 degree rotation.  I could be wrong.

That said, I think it would be a nice improvement if that value indicated the current rotation set by the slider.

**Comment by Teals53** [comment]
> I _think_ that 0 is just intended to indicate that the top of the slider represents 0 degree rotation. I could be wrong.
> 
> That said, I think it would be a nice improvement if that value indicated the current rotation set by the slider.

but its working in 15.02 so maybe its just a bug .D

**Comment by neilweinstock** [comment]
Sorry, you are correct, this is a breakage.

**Comment by Teals53** [comment]
^^

**Comment by wolsen** [comment]
From a git bisect, this appears to have been broken by commit f59ebdd0. It looks like it was a big change, so I need to look at it a bit.

**Comment by teyrana** [comment]
Hmm, I thought we fixed this? 
Is this still presemt on unstable?

**Comment by wolsen** [comment]
@teyrana yep - still present on unstable. It seems there's something to do with the update to the DoubleModel. The UnitSelector doesn't receive the events for the changes to the model so fails to repaint and update its text.

The UnitSelector adds itself as a changeListener to the model, however when the DoubleModel.setValue is invoked, it runs the code of setMethod.invoke(...) on the rocket figure and the event never gets back to the UnitSelector.

To me, it feels wrong that the UnitSelector registered for events and was never notified. A simple change would be to always call the fireStateChanged method inside of DoubleModel.setValue. However, I don't know this code well enough yet. The simple change here does indeed fix the problem, but I am not clear what all the side effects of such a change might be.

**Comment by teyrana** [comment]
Blah. I'm probably thinking of  something else.

So, yea, I tried to cut down on number of fireStateChanged calls  (to reduce the flurry of messages) but it ended up causing more trouble than it solved.

**Comment by wolsen** [comment]
A test jar is available at https://www.dropbox.com/s/j784mwjf9p7zhzm/OpenRocket-wolsen-issue-553.jar?dl=0
